### ISSUE TITLE
Doxygen confiugration file cannot be found at: ./Doxyfile

### ISSUE THREAD

**Issue by mab0189** [langroodi/doxygenize#7]
Hello, I am trying to set up a doxygenize action for one of my [repositorys](https://github.com/mab0189/Dummy_CAN_DuT). 

I followed the provided instructions and placed the Doxyfile at the root of my repository but the action keeps failing with:
`Doxygen confiugration file cannot be found at: ./Doxyfile`

Since I am new to github actions i am unsure if i did something wrong or if this is a bug.
I would greatly appreciate your help!

**Comment by langroodi** [comment]
Hi!

I checked your YAML. There is no checkout action before running the doxygenize. Usually, developers have checkout action to start their build, so doxygenize won't explicitly execute the checkout action (it is also mentioned in the guideline). Because of that your directory is empty and doxygenize cannot find anything.

You can take a look to this example how to properly add doxygenize to your pipeline:
https://github.com/langroodi/tareaSD/blob/master/.github/workflows/main.yml

Good luck ;)

**Comment by mab0189** [comment]
@langroodi Thank you very much for your help! It was clearly my fault - must have overlooked this step somehow. 
Everything works great now. What i really like about doxygenize is that it also takes care about the deployment to the github-pages. By the way i spotted a tiny typo in the Readme `GitHUb Pages home directory which contains index.html file`.

**Comment by langroodi** [comment]
No problem, nice to see that your pipeline is now green ;) Thanks for mentioning the typo. I will fix it in v1.5 which I am going to release this weekend (I hope) after do some testing.

**Comment by mab0189** [comment]
Sounds great! I will keep following this project.
